version: "3.8"
services:
  headline-backend:
    build:
      context: ./back-end/XHU_HeadLine
      dockerfile: DockerFile
    container_name: headline-backend
    environment:
      - SERVER_PORT=7111
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "7111:7111"
    restart: unless-stopped

# docker-compose.yml
  nginx:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - headline-backend
    restart: unless-stopped